name: hello-actions
 
on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest #free tier - 2,000 minutes per month

    steps:
      - name: Print message
        run: echo "Hello GitHub Actions"

  build:
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: do build
        run: echo "building app"
