name: slack-notification-demo

on:
  workflow_dispatch:
  push:
    branches:
      - slack
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - run: echo "running tests"

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - run: echo "building app"


  notify:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: elevy99927-alerts
          SLACK_USERNAME: elevy
          SLACK_TITLE: GitHub Actions Notification
          SLACK_MESSAGE: "Workflow executed successfully"
          SLACK_COLOR: good

